<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)build/obj/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)build/bin/</BaseOutputPath>
    <RestorePackagesPath>$(MSBuildThisFileDirectory)build/packages</RestorePackagesPath>
  </PropertyGroup>
</Project>
